name: Build AutoYara

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Archive JAR file
        uses: actions/upload-artifact@v2
        with:
          name: AutoYara-jar
          path: target/AutoYara-1.0-SNAPSHOT.jar
